Update requirements.txt - fix error
huggingface-hub==0.26.1 throws error
ImportError: cannot import name 'cached_download' from 'huggingface_hub'
Hence version fixed to 0.25.2